#!/bin/bash

echo '                                                                                                '
echo ' EEEEEEEEEEEEEEEEEEEEEE              AAA              ZZZZZZZZZZZZZZZZZZYYYYYYY       YYYYYYY   '
echo ' E::::::::::::::::::::E             A:::A             Z:::::::::::::::::Y:::::Y       Y:::::Y   '
echo ' E::::::::::::::::::::E            A:::::A            Z:::::::::::::::::Y:::::Y       Y:::::Y   '
echo  'EE::::::EEEEEEEEE::::E           A:::::::A           Z:::ZZZZZZZZ:::::ZY::::::Y     Y::::::Y   '
echo '  E:::::E       EEEEEE          A:::::::::A          ZZZZZ     Z:::::Z YYY:::::Y   Y:::::YYY    '
echo '  E:::::E                      A:::::A:::::A                 Z:::::Z      Y:::::Y Y:::::Y       '
echo '  E::::::EEEEEEEEEE           A:::::A A:::::A               Z:::::Z        Y:::::Y:::::Y        '
echo '  E:::::::::::::::E          A:::::A   A:::::A             Z:::::Z          Y:::::::::Y         '
echo '  E:::::::::::::::E         A:::::A     A:::::A           Z:::::Z            Y:::::::Y          '
echo '  E::::::EEEEEEEEEE        A:::::AAAAAAAAA:::::A         Z:::::Z              Y:::::Y           '
echo '  E:::::E                 A:::::::::::::::::::::A       Z:::::Z               Y:::::Y           '
echo '  E:::::E       EEEEEE   A:::::AAAAAAAAAAAAA:::::A     ZZZ:::::ZZZZZZ         Y:::::Y           '
echo '  EE::::::EEEEEEEE:::::E  A:::::A             A:::::A  Z::::::ZZZZZZZZ:::Z    Y:::::Y           '
echo 'E::::::::::::::::::::E A:::::A               A:::::A Z:::::::::::::::::Z   YYYY:::::YYYY        '
echo 'E::::::::::::::::::::EA:::::A                 A:::::AZ:::::::::::::::::Z   Y:::::::::::Y        '
echo 'EEEEEEEEEEEEEEEEEEEEEAAAAAAA                   AAAAAAZZZZZZZZZZZZZZZZZZZ   YYYYYYYYYYYYY        '
echo '                                                                                                '
echo ' Spring made eazy   Author: Funmi Ayinde                                                                                                '
echo '  :: Eazy Framework                                                                             '
echo '                                                                                                '